In [42]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import train_test_split 

#dataset = pd.read_csv("C:\\Users\\AZD\\Desktop\\merged_normalized_4_COPY1_COPY2.csv", header=0) # merged_normalized_4_COPY1
# dataset = pd.read_csv("C:\\Users\\AZD\\Desktop\\boxplot_validation_set.csv", header=0)
dataset = pd.read_csv("C:\\Users\\AZD\\Desktop\\Model Data\\Test 4-multiclass\\mergedData_MAIN.csv")
#dataset=dataset.dropna()

# merged normalized_4
X = dataset.iloc[:, 0:21]
y = dataset.iloc[:, 22]

#box-plot validation
# X = dataset.iloc[:, 0:7].values 
# y = dataset.iloc[:, 8].values

In [43]:
#print(len(dataset.rows))
print(dataset.shape)

(706, 23)


In [44]:
from numpy import nan
dataset.fillna(dataset.mean(), inplace=True)

X = dataset.iloc[:, 0:21]
y = dataset.iloc[:, 22]

#print(dataset)

In [45]:
# dividing X, y into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, train_size=0.7, random_state = 0) 
  
# training a DescisionTreeClassifier 
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 4).fit(X_train, y_train) 
dtree_predictions = dtree_model.predict(X_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, dtree_predictions) 

In [46]:
print(cm)

[[69 20  1]
 [10 55 12]
 [ 0  3 42]]


In [47]:
print(classification_report(y_test,dtree_predictions))

              precision    recall  f1-score   support

           0       0.87      0.77      0.82        90
           1       0.71      0.71      0.71        77
           2       0.76      0.93      0.84        45

    accuracy                           0.78       212
   macro avg       0.78      0.80      0.79       212
weighted avg       0.79      0.78      0.78       212



In [48]:
print(accuracy_score(y_test, dtree_predictions))

0.7830188679245284


In [16]:
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 
  
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, y_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 

In [17]:
print(cm)

[[79  0]
 [ 2 49]]


In [18]:
print(classification_report(y_test,svm_predictions))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        79
           1       1.00      0.96      0.98        51

    accuracy                           0.98       130
   macro avg       0.99      0.98      0.98       130
weighted avg       0.98      0.98      0.98       130



In [19]:
print(accuracy_score(y_test, svm_predictions))

0.9846153846153847


In [26]:
# training a KNN classifier 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(X_test, y_test) 
print(accuracy)
  
# creating a confusion matrix 
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions)

0.6846153846153846


In [21]:
print(cm)
print(knn_predictions)
print(X_test)

[[64 15]
 [26 25]]
[0 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 1 1 0 0 0
 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 1 1
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0]
      AGE  APOE4  MMSE_bl  ADAS11_bl  ADAS13_bl  Ventricles_bl  Entorhinal_bl  \
366  69.3    1.0       28        6.0        7.0   12261.000000    3520.000000   
113  77.9    0.0       30        7.0       12.0   23431.000000    2350.000000   
425  85.8    1.0       20       25.0       35.0   55669.000000    2671.000000   
320  77.2    0.0       21       21.0       32.0   38180.925926    3534.669312   
10   79.6    0.0       30        3.0        4.0   74504.000000    3213.000000   
..    ...    ...      ...        ...        ...            ...            ...   
271  65.8    1.0       28        3.0        5.0   26616.000000    3675.000000   
56   74.5    1.0       30        4.0        5.0   42478.000000    25

In [22]:
#model = knn(solver='DX_bl')
#model.fit
new_input = [[57.8,0,1,1,15,7,0.375,0.277777777777778,0.285714285714286,0.25,0.4,0.375,0.909090909090909,0.075,0.173076923076923,0.100469439997525,0.446612830865859,0.6,0.33799248307702,0.488164816360999,0.356406253240232,0.066666666666667]]
output = knn.predict(new_input)
print(new_input, output)

ValueError: query data dimension must match training data dimension

In [23]:
print(classification_report(y_test,knn_predictions))

              precision    recall  f1-score   support

           0       0.71      0.81      0.76        79
           1       0.62      0.49      0.55        51

    accuracy                           0.68       130
   macro avg       0.67      0.65      0.65       130
weighted avg       0.68      0.68      0.68       130



In [24]:
# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 
  
# accuracy on X_test 
accuracy = gnb.score(X_test, y_test) 
print(accuracy)
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, gnb_predictions)

0.9692307692307692


In [25]:
print(classification_report(y_test,gnb_predictions))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        79
           1       0.96      0.96      0.96        51

    accuracy                           0.97       130
   macro avg       0.97      0.97      0.97       130
weighted avg       0.97      0.97      0.97       130



In [86]:
print(cm)

[[42  0]
 [33 80]]


In [69]:
metrics.f1_score(X_test, y_test, labels=np.unique(y_test))

NameError: name 'metrics' is not defined