In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import train_test_split 

dataset = pd.read_csv("C:\\Users\\AZD\\Desktop\\merged_normalized_4_COPY1_COPY2.csv", header=0) # merged_normalized_4_COPY1
# dataset = pd.read_csv("C:\\Users\\AZD\\Desktop\\boxplot_validation_set.csv", header=0)
dataset=dataset.dropna()

# merged normalized_4
X = dataset.iloc[:, 0:22]
y = dataset.iloc[:, 23]

#box-plot validation
# X = dataset.iloc[:, 0:7].values 
# y = dataset.iloc[:, 8].values

In [71]:
print(len(dataset.columns))

24


In [ ]:
from numpy import nan
dataset.fillna(dataset.mean(), inplace=True)
print(dataset)

In [3]:
# dividing X, y into train and test data 
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0) 
  
# training a DescisionTreeClassifier 
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 4).fit(X_train, y_train) 
dtree_predictions = dtree_model.predict(X_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, dtree_predictions) 

In [4]:
print(cm)

[[ 28  14]
 [  9 104]]


In [75]:
print(classification_report(y_test,dtree_predictions))

              precision    recall  f1-score   support

           0       0.76      0.67      0.71        42
           1       0.88      0.92      0.90       113

    accuracy                           0.85       155
   macro avg       0.82      0.79      0.80       155
weighted avg       0.85      0.85      0.85       155



In [76]:
print(accuracy_score(y_test, dtree_predictions))

0.8516129032258064


In [77]:
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 
  
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, y_test) 
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 

In [78]:
print(cm)

[[ 22  20]
 [  7 106]]


In [79]:
print(classification_report(y_test,svm_predictions))

              precision    recall  f1-score   support

           0       0.76      0.52      0.62        42
           1       0.84      0.94      0.89       113

    accuracy                           0.83       155
   macro avg       0.80      0.73      0.75       155
weighted avg       0.82      0.83      0.81       155



In [80]:
print(accuracy_score(y_test, svm_predictions))

0.8258064516129032


In [5]:
# training a KNN classifier 
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(X_test, y_test) 
print(accuracy)
  
# creating a confusion matrix 
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions)

0.7354838709677419


In [82]:
print(cm)
print(knn_predictions)
print(X_test)

[[  7  35]
 [  6 107]]
[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 1 1]
      AGE  APOE4  PTGENDER  PTMARRY  PTEDUCAT  PTRACCAT  MEM_AVG  LANG_AVG  \
886  83.4    1.0      -1.0      1.0      18.0       5.0  0.25000  0.333333   
869  70.8    1.0      -1.0      1.0      20.0       5.0  0.56250  0.527778   
534  69.4    0.0      -1.0      1.0      16.0       5.0  0.28125  0.388889   
815  65.3    1.0      -1.0      1.0      13.0       5.0  0.34375  0.388889   
710  66.2    1.0       1.0      1.0      12.0       5.0  0.56250  0.416667   
..    ...    ...       ...      ...       ...       ...      ...       ...   
503  81.8    0.0       1.0      3.0      17.0       5.0  0.59375  0.472222   
380  68.1    1.0      -1.0      1.0  

In [64]:
#model = knn(solver='DX_bl')
#model.fit
new_input = [[57.8,0,1,1,15,7,0.375,0.277777777777778,0.285714285714286,0.25,0.4,0.375,0.909090909090909,0.075,0.173076923076923,0.100469439997525,0.446612830865859,0.6,0.33799248307702,0.488164816360999,0.356406253240232,0.066666666666667]]
output = knn.predict(new_input)
print(new_input, output)

[[57.8, 0, 1, 1, 15, 7, 0.375, 0.277777777777778, 0.285714285714286, 0.25, 0.4, 0.375, 0.909090909090909, 0.075, 0.173076923076923, 0.100469439997525, 0.446612830865859, 0.6, 0.33799248307702, 0.488164816360999, 0.356406253240232, 0.066666666666667]] [1]


In [83]:
print(classification_report(y_test,knn_predictions))

              precision    recall  f1-score   support

           0       0.54      0.17      0.25        42
           1       0.75      0.95      0.84       113

    accuracy                           0.74       155
   macro avg       0.65      0.56      0.55       155
weighted avg       0.70      0.74      0.68       155



In [84]:
# training a Naive Bayes classifier 
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, y_train) 
gnb_predictions = gnb.predict(X_test) 
  
# accuracy on X_test 
accuracy = gnb.score(X_test, y_test) 
print(accuracy)
  
# creating a confusion matrix 
cm = confusion_matrix(y_test, gnb_predictions)

0.7870967741935484


In [85]:
print(classification_report(y_test,gnb_predictions))

              precision    recall  f1-score   support

           0       0.56      1.00      0.72        42
           1       1.00      0.71      0.83       113

    accuracy                           0.79       155
   macro avg       0.78      0.85      0.77       155
weighted avg       0.88      0.79      0.80       155



In [86]:
print(cm)

[[42  0]
 [33 80]]


In [69]:
metrics.f1_score(X_test, y_test, labels=np.unique(y_test))

NameError: name 'metrics' is not defined